name: Check code
on:
    - push
    - pull_request
jobs:
    check:
        strategy:
            matrix:
                python:
                    - "3.9"
                    - "3.10"
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-python@v4
              with:
                  python-version: ${{ matrix.python }}
            - run: sudo apt install redis
            - run: make deps
            - run: make deps-dev
            - run: make type
            - run: make test
            - run: echo "X${{github.event.head_commit.message}}X" # make lint
              continue-on-error: ${{ contains(github.event.head_commit.message, 'WIP') }}
